Pull Request
majovainilla/Solo-Project-1 pull request #1
Opened 2019-08-30 21:03 UTC by majovainilla

2019-08-31 00:10 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-31 01:01 UTC, Torres-ssf requested changes
### Nicely done @majovainilla :clap: :tada: 
I must say, your page looks really nice :smile: 
But before I give you :+1: , we need to make some minor changes on it.

**[REQUIRED]**
- [x]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

**[REQUIRED]**
- [x] We need to fix the errors found by the linter, that will improve the overall quality of your code and also gives a professional look in your repository.

**[REQUIRED]**
- [x] I left comments on your code to help you fix the size of the apple products promo sections

Please kindly make these changes and submit to code review again.
Happy coding :computer:

2019-08-31 01:01 UTC, Torres-ssf commented on styles.css
> +  width: 360px;
[REQUIRED]
Change the width to `25%`, this will make the 4 images take the full available width.

2019-08-31 01:01 UTC, Torres-ssf commented on styles.css
> +  background-size: 100%;
Add the line `background-repeat: no-repeat; `.

2019-09-02 22:31 UTC, samgaco commented
#### Hi @majovainilla 

#### All the suggested changes have been well implemented, it's approved  :heavy_check_mark:  congratulations on finishing your first solo project. :clap: 

##### You may now merge to the master branch and submit the project completion form. :white_check_mark:

2019-09-04 16:01 UTC, merged